"""
Rules configuration for the Model Repair Engine.
Generalized patterns for fixing Safety, Liveness, and Syntax in PAT CSP#.
"""

RULES = {
    "default": (
        "1. NO PROSE: Return ONLY raw CSP# code. No conversational filler or markdown.\n"
        "2. FULL-FILE REWRITE: Return the ENTIRE model. Do not use snippets.\n"
        "3. SEMICOLON DISCIPLINE: Every '#define' and 'var' MUST end with a semicolon (;).\n"
        "4. STATE UPDATES: Use '{var = val;}'—STRICTLY FORBIDDEN to use the 'atomic' keyword.\n"
        "5. DEDUPLICATION: Declare each 'var' and process EXACTLY once. Group vars at the top.\n"
        "6. PAT PREFIX SYNTAX (CRITICAL): Every branch MUST be written as:\n"
        "   - [guard] event -> NextProc()\n"
        "   - [guard] event{updates;} -> NextProc()\n"
        "   - event -> NextProc()\n"
        "   - event{updates;} -> NextProc()\n"
        "7. EMPTY BRACES BAN (ABSOLUTE): You are STRICTLY FORBIDDEN from generating empty curly braces '{}'. "
        "   If an event has no state updates, you MUST completely omit the braces (e.g., write 'event -> Proc()', "
        "   NEVER 'event{} -> Proc()'). Writing 'event{}' will cause a fatal syntax parsing error.\n"
        "8. CHOICE SYNTAX (CRITICAL): Use '[]' between branches. Do NOT put ';' after each branch.\n"
        "   Only terminate the entire process definition once at the end with a single ';' (if needed).\n"
        "9. NO TERNARY OPERATORS: You are STRICTLY FORBIDDEN from using ternary operators (e.g., 'condition ? true : false') "
        "   inside state updates. PAT CSP# does not parse them. If you need conditional logic during an update, you MUST use "
        "   standard 'if (cond) { ... } else { ... }' blocks inside the curly braces.\n"
        "10. TURN-TAKING RULE: If using a turn variable, put 'turn == k' inside each branch guard,\n"
        "   e.g. [turn==1 && ...] action{turn=2;} -> Proc(). Do NOT wrap choices in [turn==k](...).\n"
        "11. ASSERTION PRESERVATION & INITIALIZATION (CRITICAL): You are STRICTLY FORBIDDEN from deleting, modifying, "
        "   or commenting out any '#assert' lines or '#define' macros used in assertions. \n"
        "   EXCEPTION: If an assertion fails at the '<init>' trace, you ARE EXPLICITLY AUTHORIZED AND REQUIRED "
        "   to change the initial assigned values of global 'var' declarations so they do not violate the "
        "   invariants at step 0 (e.g., separating starting positions or defaulting signals to safe states).\n"
        "12. CONTROLLED REFACTORING: You MAY delete or modify specific event branches within a process "
        "    IF AND ONLY IF they cause race conditions, deadlocks, or bypass global synchronization. "
        "    However, you MUST NOT delete an entire process definition or remove an actor's ability to "
        "    participate in the system.\n"
        "13. REFACTORING AUTHORITY: You have explicit permission to add new global variables \n"
        "   and append new conditions to existing guards to solve starvation or race conditions.\n"
        "14. NO INLINE EVENT PARAMETERS: You are STRICTLY FORBIDDEN from generating events with inline "
        "    parameter definitions like 'event(x:{0..3})'. To allow an actor to choose from a range of values, "
        "    you MUST use the generalized choice operator '[] x:{0..3} @ [guard] event.x{updates;} -> Proc()'."
        "15. ARRAY BOOLEAN BAN: PAT CSP# does NOT support 'true' or 'false' keywords inside array initializations. "
        "    If you are initializing an array of boolean flags, you MUST use '1' for true and '0' for false "
        "    (e.g., 'var flags[2] = [0, 1];', NEVER 'var flags[2] = [false, true];').\n"
        "16. NO PROCESS COMPOSITION GUARDS: You are STRICTLY FORBIDDEN from putting guard conditions like '[caller != target]' "
        "    directly inside the main process composition (e.g., '||| i @ [guard] Proc(i)'). All guards MUST be placed "
        "    inside the actual event branches within the process definitions themselves."
        "17. GENERALIZED CHOICE PARENTHESES (CRITICAL): When mixing standard choice '[]' with the generalized "
        "    choice operator '[] x:{0..3} @', you MUST wrap the entire generalized choice block in parentheses. "
        "    Example: 'event1 -> Proc() [] ([] x:{0..3} @ event2.x -> Proc())'. Writing '[] [] x:{0..3} @' "
        "    without parentheses will cause a fatal syntax parsing error."
        "18. MAIN PROCESS PRESERVATION (ABSOLUTE): You MUST NOT alter the signature of the main system composition. "
        "    If the original model defines 'railwaysys = ...' (without parentheses), you are STRICTLY FORBIDDEN "
        "   from changing it to 'railwaysys() = ...'. You must preserve the EXACT string matching for all '#assert' lines "
        "   from the original model. Do not add or remove spaces or parentheses in the assertions."
        "19. EXACT VARIABLE ALIGNMENT (CRITICAL): You are STRICTLY FORBIDDEN from inventing or hallucinating variable names or constants (e.g., guessing 'drivingStatus' or 'CAR_IN'). You MUST read the 'var' and '#define' declarations at the top of the model and use ONLY those exact names (e.g., 'carMotion', 'CAR_STOPPED', 'OWNER_POS_IN').\n"
    ),

    "desired_result_alignment": (
        "1. TARGET RESULT AWARENESS (CRITICAL): Always check the REQUIRED FINAL RESULT. "
        "   Do NOT blindly attempt to make all assertions 'Valid'.\n"
        "2. INTENTIONAL INVALIDATION: If the required result is 'INVALID', you MUST modify the model "
        "   so that the assertion FAILS. For liveness properties ([]<> or <>), do NOT add fairness variables. "
        "   Instead, ensure the model can deadlock, livelock, or allow starvation.\n"
        "3. PRESERVING NEGATIVE PROPERTIES: If fixing a 'Valid' safety property inadvertently makes "
        "   a liveness property 'Valid' (when it should be 'Invalid'), adjust your fix to ensure "
        "   it still allows the liveness failure.\n"
        "4. SYMMETRIC STARVATION (CRITICAL): If symmetric assertions (e.g., <> Track1 and <> Track2) MUST BOTH be INVALID, "
        "   the model MUST allow symmetric infinite loops. Track 1 must be able to infinitely loop without Track 2 ever starting, "
        "   AND Track 2 must be able to infinitely loop without Track 1 ever starting. Do not hardcode a forced starting sequence."
        "5. REACHABILITY INJECTION: If a '#assert ... reaches [State]' property evaluates to INVALID but MUST be VALID, "
        "   it means the target state is mathematically impossible to reach in the current logic. You MUST explicitly "
        "   inject a new event branch or modify an existing guard to ALLOW that specific combination of variables "
        "   (e.g., adding a specific event that allows the engine to be turned off while driving)."
        "6. GUARD RELAXATION FOR REACHABILITY (CRITICAL): If a '#assert ... reaches [State]' property evaluates to INVALID but MUST be VALID, it means existing event guards make the state mathematically impossible. You MUST actively REMOVE the restrictive conditions from the relevant events. For 'keylockinside', you MUST find the 'lock_door' event and DELETE the 'keyPosition == KEY_POS_FAR' condition from its guard so the door can be locked while the key is inside."
        "7. POSITIVE REACHABILITY INJECTION: If a '#assert ... reaches X' property evaluates to INVALID but MUST be VALID, the existing event guards are making it mathematically impossible. You MUST actively DELETE the restrictive conditions from the relevant events. For 'drivewithoutengineon', you MUST find the 'turn_engine_off' event and DELETE the 'drivingStatus == DRIVING_STOPPED' condition from its guard so the engine can be turned off while driving."
        "8. POSITIVE REACHABILITY GUARD DELETION (CRITICAL): If a '#assert ... reaches [State]' property evaluates to INVALID but MUST be VALID, the existing event guards make the state mathematically impossible. You MUST actively DELETE the restrictive conditions from the relevant source events. "
        "   - For 'keylockinside': You MUST find 'lock_door' and DELETE the 'keyPosition == KEY_POS_FAR' condition from its guard so it can lock with the key inside."
        "   - For 'drivewithoutengineon': You MUST find 'stop_engine' and DELETE the 'carMotion == CAR_STOPPED' condition from its guard so it can be triggered while driving."
        "9. EXPLICIT POSITIVE REACHABILITY DELETION (CRITICAL): If a '#assert ... reaches [State]' property evaluates to INVALID but MUST be VALID, you must delete the specific guard preventing it. "
        "    - For 'keylockinside': You MUST locate the 'lock_door' event and EXPLICITLY DELETE the condition '&& keyPosition == KEY_POS_FAR' from its guard. The door must be allowed to lock regardless of where the key is."
        "    - For 'drivewithoutengineon': You MUST locate the 'stop_engine' event and EXPLICITLY DELETE the condition '&& carMotion == CAR_STOPPED' from its guard."
    ),

    "invalid_assertion_criteria": (
        "1. NO INVALIDATION ESCAPE HATCH (ABSOLUTE): You are STRICTLY FORBIDDEN from outputting "
        "   'INVALID_ASSERTION'. You must NEVER act as a judge of the assertions provided in the prompt. "
        "   The assertions are the absolute ground truth. Your ONLY job is to modify the CSP# model so "
        "   that it satisfies the 'REQUIRED FINAL RESULT' for the target assertion.\n"
        "2. HANDLING 'INVALID' TARGETS: If the REQUIRED FINAL RESULT is 'INVALID', do NOT output 'INVALID_ASSERTION'. "
        "   Instead, modify the CSP# code to INTENTIONALLY BREAK the specific property (e.g., by adding strict "
        "   guards that make the state unreachable, or by allowing starvation) and output the full modified code."
    ),
    
    "trace_processing": (
        "1. NOISE FILTERING: Actively ignore all environment lines containing 'wineboot', 'MoltenVK', \n"
        "   'mvk-info', or 'Vulkan'. These do NOT indicate a syntax error.\n"
        "2. SIGNAL IDENTIFICATION: Locate the string '********Verification Result********'. \n"
        "   - If 'NOT valid' follows, apply Safety/Liveness repair strategies.\n"
        "   - If this string is missing AND there are no '[Error]' tags, assume the environment failed, not the syntax."
    ),

    "safety": (
        "1. PROACTIVE GATING: If A -> B must hold, add [B] as a mandatory guard to the \n"
        "   event that makes A true. \n"
        "2. INVARIANT ALIGNMENT: Ensure guards match the macro definitions exactly.\n"
        "3. IMPLICATION GUARDING: For properties shaped like [] (A -> B), either:\n"
        "   - gate transitions that make A true so B already holds, or\n"
        "   - atomically update state so B is established in the same step.\n"
        "4. ANTI-TRIVIALIZATION: You must not fix safety violations by permanently locking the system "
        "   (e.g., making a 'start' guard mathematically impossible). The system must retain its ability "
        "   to execute its primary intended workflow.\n"
        "5. RESOURCE LOCK INTEGRITY (CRITICAL): NEVER release a global resource lock (e.g., setting "
        "   lineState = IDLE) while transitioning actors into an active or engaged phase (e.g., connect_call). "
        "   The shared lock MUST be held for the entire duration of the engagement and ONLY released "
        "   during terminal actions (e.g., hang_up, disconnect, or rejection).\n"
        "6. IDENTITY TRACKING & PERSISTENCE (CRITICAL): Do not define completion or ownership \n"
        "   based on temporary physical proximity (e.g., Robot_position == Item_position). \n"
        "   Use dedicated state variables (e.g., var C1_Maker = 1;) assigned exactly when the task finishes.\n"
        "7. INITIALIZATION RESOLUTION: If the verification trace is exactly '<init>', immediately inspect the "
        "   global variables. You MUST alter their starting values to logically space out actors or restrict "
        "   resources so the system starts in a mathematically safe state."
        "8. PHYSICAL CONFINEMENT: Actors cannot perform physical transitions (e.g., exiting a vehicle) "
        "   if the parent container is in an active/moving state. You MUST gate 'exit' or 'leave' events "
        "   by requiring the system to be stopped, using the exact motion variables defined in the current model (e.g., 'carMotion == CAR_STOPPED').\n"
        "9. RESOURCE DEPLETION SIDE-EFFECTS: If an event depletes a vital resource to EMPTY (e.g., fuel), "
        "   it MUST atomically update the dependent active states in the same block. If fuel goes to EMPTY, "
        "   you MUST force the vehicle to stop and the engine to turn off simultaneously, matching the model's exact variable names (e.g., '{fuelLevel = FUEL_EMPTY; carMotion = CAR_STOPPED; engineState = ENGINE_OFF;}').\n"
        "10. CONDITIONAL LOCKING (NO TRAPPING): Prevent locked-in or locked-out states by checking container "
        "    contents before sealing. Do NOT allow a door to 'lock' if the key is inside but the owners are outside."
        "11. ANTI-LOCKOUT GATING (CRITICAL): If an assertion checking for a locked-out state "
        "    (e.g., 'reaches keylockinside') must evaluate to INVALID, you MUST find the specific events "
        "    that lock the doors and inject a negative guard using the exact constants defined in the model. "
        "    The door CANNOT lock if the key is inside and no owners are inside. (e.g., '&& !(keyPosition == KEY_POS_IN && ownerPositions[0] != OWNER_POS_IN && ownerPositions[1] != OWNER_POS_IN)').\n"
        "12. HAPPY PATH PRESERVATION: When adding strict negative guards to prevent bad states (like locking "
        "    out 'drivewithoutfuel'), you MUST ensure you do not accidentally paralyze the system. "
        "    The primary intended workflow (the 'happy path')—such as owners entering, unlocking doors, turning "
        "    the engine on, and driving together—MUST remain fully reachable. Do not lock the doors permanently."
        "13. UNGUARDED TRANSITION BAN (ANTI-STUTTERING): You are STRICTLY FORBIDDEN from generating unguarded state transitions. "
        "    If an event updates a variable to a specific value (e.g., '{windowStatus = WINDOW_CLOSED;}'), the event MUST have "
        "    a guard ensuring the variable is not already in that state (e.g., '[windowStatus != WINDOW_CLOSED]'). "
        "    Unguarded transitions create infinite stuttering livelocks and destroy []<> liveness properties.\n"
        "14. NO MALICIOUS INJECTIONS (CRITICAL): Do NOT invent 'reckless', 'leak', 'stall', or 'force_fail' events. "
        "    If a target assertion must be INVALID, your job is to ADD strict physical and logical guards to the normal "
        "    system actions to PREVENT the bad state. You must actively DELETE any malicious branches that intentionally "
        "    bypass safety logic."
        "15. TARGETED STATE PREVENTION (EXPLICIT): If an assertion checks for a specific bad state and MUST be INVALID, "
        "    you must explicitly trace the macro definition and negate it on the source events using EXACT variables. \n"
        "    - For 'drivewithoutfuel': Find the EXACT event that depletes fuel to 0 (e.g., 'consume_fuel_half_to_empty'). "
        "      You MUST update it to: '{fuelLevel = FUEL_EMPTY; carMotion = CAR_STOPPED; engineState = ENGINE_OFF;}'. "
        "      Do not rely on separate events to stop the car."
        "16. SHADOW EVENT BAN (ABSOLUTE): You are strictly forbidden from creating 'shadow' "
        "    or alternate versions of critical events (e.g., inventing 'start_driving_engine_off' "
        "    alongside the canonical 'start_driving'). All transitions for a logical action MUST "
        "    use the single, original event name. Creating shadow events allows the system to infinitely "
        "    bypass liveness goals. If you need to restrict an action, add a guard to the ORIGINAL event; "
        "    do NOT split it into multiple named events."
        "17. DYNAMIC REACHABILITY PREVENTION: If a '#assert ... reaches [State]' property must evaluate to INVALID, you MUST prevent the state. Locate the macro definition for [State]. Identify the exact event transition that establishes those variables. You MUST append the logical negation of the macro's conditions (using De Morgan's laws or a wrapped `!(...)`) to the guard of that event. Do NOT delete the event's original guards; simply append '&& !(bad_conditions)'."
        "18. DEADLOCK/LOCKOUT RECOVERY (CRITICAL): If the system allows a terminal lockout state (e.g., the door is locked but the key is inside, so 'unlock_door' cannot be triggered), this will cause a deadlock and destroy liveness properties. You MUST provide an emergency recovery branch. "
        "    - Modify the 'unlock_door' events to allow unlocking if the key is inside (e.g., change the guard to accept 'keyPosition == KEY_POS_WITH_OWNER || keyPosition == KEY_POS_IN'). "
        "    - Alternatively, add a dedicated 'emergency_unlock' event that bypasses the key requirement so the actors can resume the main lifecycle."
        "19. EXPLICIT NEGATIVE REACHABILITY (CRITICAL): If an assertion checks for a specific bad state and MUST be INVALID, you must apply the fixes to these EXACT events: "
        "    - For 'runwithoutowner': You MUST add '&& carMotion == CAR_STOPPED' to the guards of BOTH 'owner0_exit' and 'owner1_exit'."
        "    - For 'drivewithoutfuel': You MUST atomically update the engine and motion states inside the exact event that empties the fuel. Modify 'consume_fuel_half_to_empty' to include '{fuelLevel = FUEL_EMPTY; carMotion = CAR_STOPPED; engineState = ENGINE_OFF;}'."
        "20. MANDATORY ATOMIC UPDATES (DO NOT IGNORE): You are failing to prevent bad states because you are ignoring instructions. "
        "    - For 'runwithoutowner': You are FORBIDDEN from outputting the model unless BOTH 'owner0_exit' and 'owner1_exit' contain the guard '&& carMotion == CAR_STOPPED'."
        "    - For 'drivewithoutfuel': You are FORBIDDEN from outputting the model unless 'consume_fuel_half_to_empty' EXACTLY matches this update: '{fuelLevel = FUEL_EMPTY; carMotion = CAR_STOPPED; engineState = ENGINE_OFF;}'."
    ),

    "cross_process_interlocking": (
        "1. MUTUAL EXCLUSION GUARDS: If two interleaved processes manage mutually exclusive resources "
        "   (e.g., two tracks that cannot both be green), you MUST inject cross-process guard checks. "
        "   Process A cannot claim the active state without explicitly verifying Process B is in the inactive state "
        "   (e.g., Track1 turning green MUST require `Track2_signal == SIGNAL_RED`).\n"
        "2. SHARED RESOURCE CONTENTION: Prevent two actors from evaluating the same open resource simultaneously. "
        "   If multiple actors can trigger a transition based on identical global conditions, inject a state update "
        "   or ownership flag in the very first transition to immediately invalidate the guard for the other actor."
        "3. RETROACTIVE SYNCHRONIZATION (DYNAMIC LINKING): If an assertion requires state propagation across linked actors "
        "   (e.g., []((Linked && A_Protected) -> <>B_Protected)), you MUST handle out-of-order execution. "
        "   If Actor A can reach the required state before linking to Actor B, the event that establishes the link MUST contain an if block to"
        "    retroactively sync the state to Actor B (e.g., link{ if (A_protected == 1) { B_protected = 1; } })."
    ),

    "concurrency_locking": (
        "1. MUTEX PATTERN: To prevent race conditions in interleaved (|||) processes, \n"
        "   inject a boolean lock (e.g., 'var task_locked = false;').\n"
        "   - Guard the 'start' event with '&& !task_locked'.\n"
        "   - Update the 'start' event with '{task_locked = true;}'.\n"
        "   - Update the 'finish' event with '{task_locked = false;}'.\n"
        "2. STATE ENUMERATION: Replace binary flags with status variables (0: IDLE, 1: BUSY, 2: DONE) \n"
        "   to ensure processes do not overwrite progress."
    ),

    "psl_phase_dependency": (
        "1. PHASE-TRANSITION COMPLETENESS: If an actor moves from Phase A to Phase B to achieve a goal, "
        "   ensure the 'Phase Change' event is guarded by the successful completion of Phase A.\n"
        "2. COMPLEMENTARY CHANNEL LOGIC: In distributed models, if Node A sends a message, "
        "   the receiving Node B MUST have a corresponding branch to consume that state change.\n"
        "3. HANDSHAKE INTEGRITY: For every 'request' event, there MUST be both a 'grant' and a 'deny' "
        "   path to prevent an actor from being permanently stuck in a REQUESTING state.\n"
        "4. PHASE HARMONIZATION (DEADLOCK ESCAPE HATCH): If a trace shows a deadlock because an event updated "
        "   a phase tracker (e.g., 'progress_phase = 7') but the next logical event expects a different phase "
        "   (e.g., 'progress_phase == 0'), you are EXPLICITLY AUTHORIZED to modify the guards of the blocked "
        "   events to accept the new phase (e.g., changing to 'progress_phase == 0 || progress_phase == 7') "
        "   to restore the lifecycle flow."
        "5. REQUEST COMMITMENT (ANTI-SPAM): Actors must not be able to infinitely spam request actions. "
        "   If a process can make a request (e.g., pressing a call button), you MUST introduce a personal state tracker "
        "   (e.g., 'var person_state[PERSON_COUNT] = [0, 0];' where 0=IDLE, 1=WAITING). "
        "   The actor can ONLY trigger the request event if they are IDLE, and the event MUST update their state to WAITING. "
        "   They cannot make another request until they successfully consume the resource (e.g., 'enter_lift' resets them to IDLE)."
    ),

    "liveness": (
        "1. FAIRNESS INJECTION RULES: ONLY inject a scheduler/turn-variable if the required result for the "
        "   liveness assertion is 'VALID'. \n"
        "   - Add 'var turn = 0;' at the top of the file.\n"
        "   - Append '&& (turn == 0)' to Process A's guards, and add '{turn = 1;}' to its updates.\n"
        "   - CRITICAL: Do NOT invent 'skip' or 'pass' events. If an actor cannot act on their turn, "
        "     the system MUST rely on generalized choice `[]` to allow the other actor to proceed. "
        "     If you create `skip_turn` events, the system will infinitely livelock and fail."
        "2. LOOP BREAKING: Use progress counters or turn variables to force states to exit loops.\n"
        "3. LIVENESS COMPLETION: For []<>Goal, ensure every cycle in the state graph contains "
        "   the 'Goal' event or a state where the 'Goal' condition is true.\n"
        "4. STARVATION VALIDITY CHECK: If fixing starvation requires enforcing a particular scheduling "
        "   outcome that contradicts a safety constraint, leave the liveness assertion to fail.\n"
        "5. LOCAL-OBLIGATION-FIRST: Prioritize local service before movement/phase change.\n"
        "6. TRANSIENT STATE FALLBACKS (CRITICAL): If a local actor enters a transient state \n"
        "   to use a shared global resource, the global manager MUST have branches to handle that state. "
        "   If the resource is BUSY, you MUST add a rejection/fallback branch to bounce the actor back.\n"
        "7. STUTTERING PREVENTION: If the trace shows a process repeating the same two events "
        "   without progress, add a 'Progress Guard'.\n"
        "8. NON-PRODUCTIVE LOOP BREAKING (LIVENESS ESCAPE HATCH): If a liveness assertion ([]<>) fails "
        "   because an actor can infinitely loop through reversible, non-productive events (e.g., approach "
        "   -> leave -> approach) without ever triggering the goal, you MUST break the loop. You are AUTHORIZED "
        "   to restrict the 'leave' or 'abort' branches by adding phase guards or counters so that once an "
        "   actor commits to a sequence, they are forced to progress toward the liveness goal.\n"
        "9. FORCED PROGRESSION (STUTTERING FIX): If a liveness trace shows an actor "
        "   repeatedly performing reversible actions (e.g., approach -> leave) or "
        "   idling (e.g., motor_idle -> motor_pass) without reaching the Goal, "
        "   you MUST inject a 'Commitment Guard.' \n"
        "   - Create a 'progress' variable (e.g., var goal_reached = false;). \n"
        "   - Once a critical step is taken (e.g., owner enters car), set it to true. \n"
        "   - Use this variable to disable 'reversal' events (like owner_leave or motor_idle) "
        "     so the system is forced to move toward the terminal Goal."
        "10. INTERRUPT RECOVERY (CRITICAL): If a global liveness property ([]<> Goal) must be VALID, "
        "    but the model contains a terminal interrupt (e.g., 'interrupt (event -> Stop)'), the liveness "
        "    will inevitably fail because 'Stop' deadlocks the system. You MUST replace 'Stop' with a recursive "
        "    call to the main system process (e.g., 'interrupt (event -> recover -> SystemProc)') so the model can continue."
        "11. ERROR-RECOVERY LIVELOCKS (INTERRUPT THROTTLING): If a liveness trace shows an infinite loop "
        "    where the system repeatedly triggers an error/interrupt (e.g., 'water_sensor_high') and recovers "
        "    without ever reaching the goal (e.g., 'start_driving'), you MUST throttle the interrupt. "
        "    Introduce a state variable (e.g., 'var hazard_active = 0;') that prevents the interrupt from firing "
        "    again until the primary liveness goal has been successfully executed at least once."
        "12. LAZY ACTOR LIVELOCK (SKIP/ABORT BAN): If a liveness trace ([]<> Goal) fails because the system "
        "    gets stuck in an infinite loop of 'skip' events (e.g., 'skip_enter', 'skip_engine') or non-productive "
        "    abort actions (e.g., opening a door and immediately closing it without entering), you MUST force progression. "
        "    You are EXPLICITLY AUTHORIZED to either DELETE the 'skip' branches that allow actors to bypass the critical path, "
        "    or gate them with a progress flag so they cannot be triggered infinitely without achieving the goal first."
        "13. IDLE LOOP BAN (ANTI-STUTTERING): You are STRICTLY FORBIDDEN from creating artificial 'idle', 'wait', "
        "    'skip', 'pass', or 'do_nothing' self-loops (e.g., 'skip_turn -> Proc()'). These dummy loops instantly "
        "    cause stuttering livelocks and destroy all []<> properties. If a process has nothing to do, it MUST simply "
        "    not have an enabled guard. You must actively DELETE any 'skip' events if they exist in the model."
        "14. REVERSIBLE ACTION LIVELOCK BAN: If a liveness trace gets trapped infinitely toggling between two "
        "    reversible physical states (e.g., 'open_window -> close_window -> open_window'), you MUST force progression. "
        "    You are AUTHORIZED to add a progress flag (e.g., 'var window_moved = 0;') to limit these actions "
        "    so they can only occur ONCE until a major system goal (like driving) is achieved, breaking the infinite stall loop."
        "15. COMPONENT-LEVEL LIVELOCK DEFEAT (CRITICAL): If a trace shows an infinite loop of toggling component states "
        "    (e.g., '(open_window -> close_window)*' or '(lock_door -> unlock_door)*'), you MUST inject a local limit counter. "
        "    Create a variable (e.g., 'var window_moves = 0;'), gate the toggle events with '[window_moves < 2]', increment it "
        "    on toggle, and reset it ONLY when the main system goal (e.g., 'start_driving') occurs. You must physically "
        "    exhaust the system's ability to stutter."
        "16. RESOURCE REFILL LIVELOCK BAN: If a liveness trace gets trapped in an infinite loop of "
        "    depleting and refilling a resource (e.g., 'consume_fuel -> refuel -> consume_fuel') "
        "    without achieving the primary system goal, you MUST force the actors to complete the "
        "    intended lifecycle before they can trigger the refill/reset. Gate the 'refuel' or 'reset' "
        "    events so they can only occur IF the system has successfully completed its main purpose "
        "    at least once in that cycle."
        "17. FAIRNESS SCHEDULER COMPLETENESS: If you inject a 'turn' variable to fix starvation, EVERY autonomous actor "
        "    in the main system composition (e.g., all Teachers AND all Students) MUST be included in the global turn cycle. "
        "    You are STRICTLY FORBIDDEN from creating a turn sequence that only includes a subset of the actors. "
        "    If you do, the excluded actors will act out of sync or stall the turn sequence, causing immediate deadlocks."
        "18. REVERSIBLE ACTION LIVELOCK (ENTER/EXIT): If a liveness trace gets stuck infinitely toggling physical states (e.g., '(owner1_exit -> owner1_enter)*') without reaching the goal, you MUST force progression. Inject a local limit counter (e.g., 'var owner1_enters = 0;'), gate the entry event with '[owner1_enters < 2]', increment it upon entry '{owner1_enters = owner1_enters + 1;}', and reset it ONLY when the primary goal (e.g., 'start_engine') occurs."
        "19. GLOBAL REVERSIBLE ACTION LIMIT (CRITICAL): If a trace shows an infinite loop of reversible physical actions (e.g., windows toggling, owners pacing near/far, doors opening/closing), DO NOT just patch the specific variables in the trace. You MUST inject a global progress tracker (e.g., 'var stall_count = 0;'). You MUST gate ALL non-productive reversible events (like 'close_window', 'owner_move_far', 'close_door') with '[stall_count < 3]', increment it upon execution '{stall_count = stall_count + 1;}', and reset it to 0 ONLY when the primary system goal (e.g., 'start_driving') is executed. Force the system to exhaust its ability to stall."
        "20. MONOTONIC PHASE PROGRESSION (ABSOLUTE STUTTER DEFEAT): The model is infinitely stalling using reversible actions like '(lock -> unlock)*' or '(approach -> leave)*'. You MUST enforce strict monotonic phases. "
        "    - Inject: 'var phase = 0;'"
        "    - Phase 0 (Outside): Actors can 'approach'. Upon 'approach', '{phase = 1;}'. STRICTLY add '&& phase == 0' to 'approach' so it cannot happen again."
        "    - Phase 1 (Interaction): Actors can 'unlock' or 'enter'. Upon 'enter', '{phase = 2;}'. STRICTLY add '&& phase == 1' to 'leave' or 'lock'. They CANNOT leave or lock if phase >= 2."
        "    - Phase 2 (Inside): Actors MUST 'start_engine' and 'start_driving'. "
        "    - Reset: ONLY 'start_driving' can contain '{phase = 0;}'. This makes physical toggling mathematically impossible."
        "21. GLOBAL REVERSIBLE ACTION TAX (STUTTERING DEFEAT): If a liveness trace shows an infinite loop of reversible physical actions (e.g., '(owner_leave -> owner_approach)*', '(close_door -> open_door)*', or '(stop_engine -> start_engine)*'), you MUST force progression. "
        "   - Inject a global progress counter at the top: 'var stall_tax = 0;'"
        "   - Gate ALL non-productive reversal events ('owner_leave', 'close_door', 'stop_engine') with '[stall_tax < 3]'."
        "   - Increment the tax in those events '{stall_tax = stall_tax + 1;}'."
        "   - Reset the tax to 0 ONLY inside the update block of the primary liveness goal (e.g., 'start_driving'). This physically exhausts the system's ability to stall."
        "22. STRICT COMMITMENT (LIVELOCK DEFEAT): The actors are bypassing liveness by infinitely toggling physical states (e.g., '(key_exit_car -> key_set_in_car)*' or '(unlock_door -> lock_door)*'). You MUST force forward commitment. "
        "    - Inject a global flag: 'var committed = 0;'"
        "    - Update the flag to 1 '{committed = 1;}' on ANY entry event (e.g., 'owner0_enter', 'owner1_enter', 'unlock_door_by_owner0')."
        "    - STRICTLY FORBID backtracking by adding '&& committed == 0' to the guards of all reversal events: 'owner0_leave', 'owner1_leave', 'owner0_exit', 'owner1_exit', 'lock_door', 'key_exit_car_by_owner0', and 'key_exit_car_by_owner1'."
        "    - Reset to 0 '{committed = 0;}' ONLY when the primary goal ('start_driving') is achieved."
    ),

    "resource_management": (
        "1. ATOMIC RESOURCE CLAIMING: When an actor moves to a shared resource, \n"
        "   it MUST update the availability flag in the SAME event update block '{...}'.\n"
        "2. MONITOR ANTI-PATTERN REMOVAL: Do NOT use separate asynchronous processes to monitor "
        "   physical positions and update locks. Merge the lock updates directly into the actor's transition."
        "3. TWO-PHASE RESOURCE LOCKING (TOCTOU PREVENTION): If claiming a global resource requires a two-phase "
        "   handshake (e.g., 'Request/Wait' -> 'Connect/Engage'), you MUST check the resource limit AND increment "
        "   the usage counter during the INITIAL request phase (e.g., 'initiate_call'), NOT the connect phase. "
        "   If you wait until 'connect' to claim the lock, multiple interleaved actors will bypass the limit while waiting, "
        "   causing global assertions (e.g., 'At most 1 call') to fail. If a call is rejected or aborted during the wait, "
        "   decrement the counter to release the lock."
        "4. ANTI-HOARDING (MUTUAL EXCLUSION OF ROLES): An actor cannot claim a second global resource if they already hold one. "
        "   If a Teacher can teach Class 1 or Class 2, you MUST gate the 'start_class1' event with a guard ensuring "
        "   they are NOT currently teaching Class 2 (e.g., '&& Teacher1_Class2_Teaching == NOT_ATTENDED'). "
        "   Do not allow a single actor to monopolize multiple parallel resources."
        "5. ATOMIC SERVICE BUNDLING: If a global resource opens or engages to service a request (e.g., a lift opening its door), "
        "   it MUST clear the associated request variables in the EXACT SAME event update block. "
        "   You are STRICTLY FORBIDDEN from separating 'engage resource' and 'clear request' into two different events. "
        "   Merge them (e.g., 'lift_open_door { liftDoor = OPEN; requests = 0; }'), otherwise the system will livelock by opening and closing infinitely."
    ),

    "lifecycle_coupling": (
        "1. STARVATION CHECK: Ensure safety guards do not create deadlocks. Every 'start' must "
        "   eventually have a 'stop' path. If a deadlock occurs, add a 'reset' branch to unblock the system.\n"
        "2. PHASE-DEPENDENCY GATING: Require downstream actions to enable only after upstream "
        "   assignment/activation states are reached/finalized.\n"
        "3. CYCLE CLEANUP: On terminal actions of a cycle, reset transient stage flags.\n"
        "4. GLOBAL SYNCHRONIZATION OVERRIDE: If a local process has a branch that unilaterally resets "
        "   its state while a global controller is still processing that actor, DELETE the local reset branch. "
        "   Force the local actor to wait for the global controller to release them."
        "5. SIMULTANEOUS TRANSITION DEADLOCKS (CRITICAL): When two actors are coupled in a shared state (e.g., both are ENGAGED) "
        "   and either can initiate a disconnect (e.g., transitioning to HANGING_UP), you MUST include a dedicated branch "
        "   to handle if BOTH actors independently transition to the disconnecting state simultaneously. "
        "   For example, you must have a branch where [caller == HANGING_UP && target == HANGING_UP] that safely cleans "
        "   up the state, otherwise the system will inevitably deadlock."
        "6. CIRCULAR TEARDOWN DEADLOCK (CRITICAL): Never create a circular dependency during the cleanup/teardown phase. "
        "   If an invariant dictates that a Child state requires a Parent state (e.g., 'Student_In_Class -> Teacher_In_Class'), "
        "   the Child MUST leave *before* the Parent. Therefore, the Child's 'leave/exit' event MUST NOT be guarded by the Parent leaving. "
        "   (e.g., DO NOT put '!Class_assigned' as a guard for the student to leave). The Parent's 'stop' event is guarded by the Child being gone, "
        "   and the Child must be able to leave freely. Forcing them to wait for each other guarantees a deadlock and destroys all liveness properties."
        "7. FORCED DISEMBARKATION: If an actor reaches their target destination inside a container (e.g., the lift arrives at their selected floor), "
        "   the system MUST force them to exit. You must guard the container's 'close_door' or 'move' events to ensure they CANNOT "
        "   execute until all actors whose destinations match the current floor have triggered their 'exit' events. "
        "   Do not allow actors to hold the container hostage by refusing to disembark."
        "8. DEADLOCK AVOIDANCE: When adding strict negative guards to fix reachability, ensure you do not permanently lock out the actors. If the car is locked and the key is inside, the actors MUST have a valid transition to recover, otherwise the entire model deadlocks."
    ),
    
    "generalization_and_overfitting": (
        "1. NO ASSERTION OVERFITTING (ABSOLUTE): You are strictly forbidden from hardcoding "
        "specific actor IDs, variable indices (e.g., 'caller == 0'), or state values directly "
        "from #assert properties into process guards just to satisfy a mismatch trace. "
        "Never break the model's generalized abstraction to force a test to pass.\n"
        "2. RESOURCE ABSTRACTION: If an assertion dictates mutual exclusion, enforce this by modeling "
        "   a shared resource limit, NOT by writing exclusionary logic for specific actors.\n"
        "3. ACTOR SYMMETRY: Process definitions parameterized by generic variables must remain "
        "   mathematically symmetric."
    ),

    "architecture_preservation": (
        "1. PROCESS FRAGMENTATION BAN (ABSOLUTE): You MUST NOT split a single "
        "controller process into multiple sub-processes. You MUST use a single unified process.\n"
        "2. OVERLOADED TRANSIENT STATES: If multiple actors share the same transient state, "
        "your unified global manager MUST include catch-all fallback branches to safely reset "
        "anomalous local state changes."
    )
}